name: Deploy CodeChecker VSCode extension

# Triggers the workflow when a new release is published.
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish extension
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn run test

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create vsix package
        if: success()
        id: build
        run: |
          yarn run vsce package --no-git-tag-version --yarn ${{ steps.get_version.outputs.VERSION }}
          echo ::set-output name=vsixPath::$(readlink -f *.vsix)

      - name: Create vsix artifact
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: vsix-package
          path: ${{ steps.build.outputs.vsixPath }}

      - name: Publish to Open VSX Registry
        if: success()
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.build.outputs.vsixPath }}

      - name: Publish to Visual Studio Marketplace
        if: success()
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.build.outputs.vsixPath }}
