name: codechecker-vscodeplugin-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request, workflow_call]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install CodeChecker
        run: |
          sudo apt install -y clang-tidy
          sudo snap install codechecker --classic
          sudo snap alias codechecker CodeChecker
          CodeChecker version
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: yarn run test
