name: codechecker-vscodeplugin-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request, workflow_call]

jobs:
  version:
    name: Version dummy
    runs-on: ubuntu-22.04
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::0.0.0-$(echo ${GITHUB_SHA} | head -c 7)

  package:
    needs: [version]
    uses: ./.github/workflows/package.yml
    with:
      version: ${{ needs.version.outputs.version }}

  test:
    name: Tests
    runs-on: ubuntu-22.04
    needs: [package]

    steps:
      - uses: actions/checkout@v3

      - name: Enable Yarn 2
        run: yarn set version stable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install CodeChecker
        run: |
          sudo apt install -y clang-tidy
          sudo snap install codechecker --classic
          sudo snap alias codechecker CodeChecker
          CodeChecker version

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: yarn run test
