name: codechecker-vscodeplugin-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request]

jobs:
  version:
    name: Get version number
    runs-on: ubuntu-22.04
    steps:
      - name: Get the version
        id: get_version
        run: echo version=0.0.0-$(echo ${GITHUB_SHA} | head -c 7) >>$GITHUB_OUTPUT

  package:
    needs: [version]
    uses: ./.github/workflows/package.yml
    with:
      version: ${{ needs.version.outputs.version }}

  test:
    uses: ./.github/workflows/test.yml

  # Needed to run the packaging and tests in parallel
  test-commit:
    name: Run commit tests
    needs: [package, test]
    runs-on: ubuntu-22.04
    steps:
      - name: Do nothing
        run: ":"
